### ISSUE TITLE
Testers are getting this error

### ISSUE THREAD

**Issue by MagicalMS** [dustin-s/gamma#16]
At least two of the testers are getting this error when they attempt to download the app.
What can I do to fix it?
![image0](https://user-images.githubusercontent.com/88515183/187048188-b1fba2e8-20a5-45f8-9137-d6aa1f3e68bd.jpeg)

**Comment by Chip-L** [comment]
I think this is mine to fix. This looks similar to the error I'm working on.
Chip Long Phone (Cell): 720-289-4751 

    On Saturday, August 27, 2022 at 03:19:24 PM MDT, MagicalMS ***@***.***> wrote:  
 
 


Assigned #16 to @Chip-L.

**Comment by Chip-L** [comment]
Gave new build, should be fixed. retest and close if fixed.
