### ISSUE TITLE
Priority 2: Edit button 

### ISSUE THREAD

**Issue by MagicalMS** [dustin-s/gamma#21]
The edit button for the POI description is cut off by the screen. 
Problem was found on a Samsung S10. 
- If it's still a popular model it needs fixed.
- If barely anyone has it, it doesn't.

**Comment by Chip-L** [comment]
I think this needs looked in to. We may not be able to fix it entirely, but even on my phone, I do see the boxes aren't aligning correctly. This is a style issue, can you fix it?

**Comment by MagicalMS** [comment]
I’ll see what I can do.

**Comment by Chip-L** [comment]
@MagicalMS isn't this fixed with pull request #23?
